/** @format */

export const Data = [
  {
    id: 1,
    name: "Deepak",
    image: "/astrologer1.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25",
    offer: "FREE",
    checkImage: "/check.svg",
    waitingTime: "",
  },
  // Add other card data here, example:
  {
    id: 2,
    name: "Pushpak",
    image: "/astrologer2.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25",
    offer: "FREE",
    checkImage: "/check.svg",
    waitingTime: "",
  },
  {
    id: 3,
    name: "Tripti",
    image: "/astrologer3.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25",
    offer: "₹5/Min",
    checkImage: "/check.svg",
    waitingTime: "",
  },
  {
    id: 4,
    name: "Aarohi",
    image: "/astrologer4.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "",
  },
  {
    id: 5,
    name: "Mahima",
    image: "/astrologer5.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "Wait - 7 min",
  },
  {
    id: 6,
    name: "Khusbo",
    image: "/astrologer6.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "Wait - 7 min",
  },
  {
    id: 7,
    name: "Aarohi",
    image: "/astrologer4.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "",
  },
  {
    id: 8,
    name: "Mahima",
    image: "/astrologer5.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "Wait - 7 min",
  },
  {
    id: 9,
    name: "Khusbo",
    image: "/astrologer6.svg",
    rating: 4.5,
    specialties: "Vedic, Numerology...",
    languages: "Hindi, English, Gujr...",
    experience: "Exp: 10 Years",
    price: "₹25/Min",
    offer: "",
    checkImage: "/check.svg",
    waitingTime: "Wait - 7 min",
  },
];
